//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zero_hunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectRequest
    {
        public int id { get; set; }
        public Nullable<int> restaurant_id { get; set; }
        public string food_type { get; set; }
        public int quantity { get; set; }
        public System.DateTime max_preservation_time { get; set; }
        public string collection_status { get; set; }
        public Nullable<int> collection_employee_id { get; set; }
        public Nullable<System.DateTime> collection_time { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
